---
- name: Run Certbot with DNS Challenge
  community.docker.docker_container:
    name: certbot_dns
    image: certbot/certbot
    command: >
      certonly --webroot -w {{ item.path }}
      --email jawad@questra.digital
      --agree-tos
      -d {{ item.domain }}
    volumes:
      - "/home/user/nginx/certbot/letsencrypt:/etc/letsencrypt"
      - "/home/user/nginx/www/{{ item.name }}:{{ item.path }}"
    auto_remove: yes
  loop: "{{ domains }}"

- name: Copy HTTPS Nginx configuration files
  template:
    src: ../../setup_nginx/template/https_configs/app.conf.j2
    dest: "/home/user/nginx/conf/{{ item.name }}.conf"
    mode: "0644"
  loop: "{{ domains }}"

- name: Restart nginx server
  community.docker.docker_container:
    name: nginx_container
    restart: true
    state: started