all:
  hosts:
    target_host:
      ansible_host: 192.168.100.100
      ansible_user: vagrant
  vars:
    registry_url: https://index.docker.io/v1/
    registry_username: dockerRegisteryUser
    registry_password: dockerRegisterPasswordOrAccessToken