version: "3.9"

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "12345678"]
    ports:
      - "6379:6379"
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ dashboard
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminPassword
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  email-service:
    image: ghcr.io/bilal-os/my-repo/email-service:latest
    container_name: email-service
    env_file:
      - ./email-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8082:8082"
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api-gateway:
    image: ghcr.io/bilal-os/my-repo/api-gateway:latest
    container_name: api-gateway
    env_file:
      - ./api-gateway/.env
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "8087:8087"
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  auth-service:
    image: ghcr.io/bilal-os/my-repo/auth-service:latest
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "8083:8083"
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  otp-service:
    image: ghcr.io/bilal-os/my-repo/otp-service:latest
    container_name: otp-service
    env_file:
      - ./otp-service/.env
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "8081:8081"
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16