---
- name: Use the VM's assigned IP
  hosts: all
  become: true # Escalate privilege escalation (sudo) for all tasks
  vars_files: # Loads external variables
    - vars/users.yml
    - vars/domains.yml
  roles:
    - role: common_config
    - role: ssh_users
      tags: [all, users]
    - role: install_docker
      tags: [all, docker]
    - role: setup_nginx
      tags: [all, nginx]
    - role: setup_ssl